### ISSUE TITLE
Light mode colors

### ISSUE THREAD

**Issue by Jrmuys** [Inertia-Printers/InertiaPrintersWebsite#32]
There are a couple of places where colors are not showing up correctly in light mode.

- Login page
Text and input colors do not adjust correctly in light mode

- Queue page
Pills in queue components are not displaying correctly.

- Printer specifics page 
Some text and background combinations are not updating correctly.

**Comment by TheDunco** [comment]
Most of these I already fixed! I pushed a style changes update to the main branch
